//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esteban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int uid_cliente { get; set; }
        public string nombre { get; set; }
        public string documento { get; set; }
        public string telefono { get; set; }
        public string eliminado { get; set; }
    }
}
